// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameSubmission = "submission"

// Submission mapped from table <submission>
type Submission struct {
	ID          int64     `gorm:"column:id;primaryKey;autoIncrement:true;comment:自增ID" json:"id"`                         // 自增ID
	ContainerID string    `gorm:"column:container_id;not null;comment:容器ID" json:"container_id"`                          // 容器ID
	QuestionID  int64     `gorm:"column:question_id;not null;comment:题目ID" json:"question_id"`                            // 题目ID
	CreatedAt   time.Time `gorm:"column:created_at;not null;default:CURRENT_TIMESTAMP(3);comment:创建时间" json:"created_at"` // 创建时间
	UpdatedAt   time.Time `gorm:"column:updated_at;not null;default:CURRENT_TIMESTAMP(3);comment:更新时间" json:"updated_at"` // 更新时间
}

// TableName Submission's table name
func (*Submission) TableName() string {
	return TableNameSubmission
}
